application: colabroutes
version: 1
runtime: python27
api_version: 1
threadsafe: 1

handlers:
- url: /assets/(.*)
  static_files: public/assets/\1
  upload: public/assets/(.*)

- url: /(.*\.html)
  static_files: public/\1
  upload: public/(.html)

- url: /offer(.*)
  script: handlers.offer.app
 
- url: /search(.*)
  script: handlers.search.app

- url: /query(.*)
  script: handlers.query.app

- url: /user(.*)
  script: handlers.user.app

- url: .*
  script: main.app

error_handlers:
- file: public/error.html

inbound_services:
- warmup
    
libraries:
- name: webapp2
  version: 2.5.1
